if(WIN32)
  if(MSVC)
    set(CMAKE_CXX_FLAGS_DEBUG_INIT "/D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 /utf-8")
    set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "/MT /O1 /Ob1 /D NDEBUG /utf-8")
    set(CMAKE_CXX_FLAGS_RELEASE_INIT        "/MT /O2 /Ob2 /D NDEBUG /utf-8")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/MT /Zi /Od /Ob1 /D NDEBUG /utf-8")
  elseif(MINGW)
    set(CMAKE_CXX_FLAGS_RELEASE_INIT "-D_MT -O3 -DNDEBUG")
  else()
    if ("!${CMAKE_CXX_COMPILER_ID}" STREQUAL "!Clang")
      set(CMAKE_CXX_FLAGS_DEBUG_INIT "-O0 -g -Xclang -gcodeview -D_DEBUG -D_MT")
      set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-D_MT -Os -DNDEBUG")
      set(CMAKE_CXX_FLAGS_RELEASE_INIT "-D_MT -O3 -DNDEBUG")
      set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-D_MT -O0 -DNDEBUG -g -Xclang -gcodeview")
    else()
      set(CMAKE_CXX_FLAGS_RELEASE_INIT "-D_MT -O3 -DNDEBUG")
    endif()
    set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-Wno-error=deprecated-declarations")
  endif()
endif()
